cask_args appdir: "/Applications"

brew "mas"
brew "tree"
brew "neovim"
brew "ripgrep"

cask "amethyst"
cask "google-chrome"
cask "firefox"
cask "visual-studio-code"
cask "slack"
cask "wezterm"
cask "obsidian"
cask "raycast"
